config/routes.rb
ReporteDeHoras::Application.routes.draw do

  


devise_for :users
resources :courses  
resources :reports

resource :user, except: [:index, :destroy, :new, :create] do
  resources :reports,     only: [] do
    collection do
    	get 'monthly_reports'
      get 'my_reports'
      get 'calendar_reports'
    end
  end
end


 devise_scope :user do
   root to: "devise/sessions#new"
 end


end

app/models/report.rb
class Report < ActiveRecord::Base

	belongs_to :user
	belongs_to :course
	has_many   :calendars
	validates  :course_start_time, presence: true



	def course_name
		@course_name = Course.find(self.course_id).name
	end

	def add_days
		course_days = []
		course_days << Calendar.where("week_day = ? AND period = ?", "#{self.week_day}", "#{self.period}")
		course_days.flatten!
		course_days.each do |day|
			new_day = day.dup
			new_day.report_id = self.id
			new_day.save
		end
	end

	def month_interval(requested_month_start, requested_month_finish)
		uno = Calendar.where("month = ? AND day_of_month = ?", "#{requested_month_start}", 25).first.id
    dos = Calendar.where("month = ? AND day_of_month = ?", "#{requested_month_finish}", 25).first.id
    @month_interval = []
    self.calendars.each do |day|
    	if day.month == requested_month_start && day.day_of_month > 25
    		@month_interval << day
    	end
    	if day.month == requested_month_finish && day.day_of_month <= 25
    		@month_interval << day
    	end
	end
	@month_interval
end

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController

  before_action :authenticate_user!

  def new
    @month = Time.now.month
    if    [1,2,3,4].include?(@month) then @default_period = 1 end
    if    [5,6,7,8].include?(@month) then @default_period = 2 end
    if [9,10,11,12].include?(@month) then @default_period = 3 end    
  @my_reports = current_user.reports
  @array_for_options = Course.array_for_options
  @user = current_user
  @array_for_days = Course.array_for_days
  @array_for_period = [["Invierno", 1], ["Verano", 2], ["Otoño", 3]]
  end

  def my_reports
    @my_reports = current_user.reports
    @my_reports
  end

  def calendar_reports
    @my_reports = current_user.reports
    @my_reports.each do |report|
      report.add_days
    end
    @my_reports = current_user.reports.where("period = ?", params[:period])
    @period = params[:period]

  end


  def monthly_reports
    @start  = params[:start]
    @finish = params[:finish]
    #uno = Calendar.where("month = ? AND day_of_month = ?", "#{@requested_month_start }", 25).first.id
    #dos = Calendar.where("month = ? AND day_of_month = ?", "#{@requested_month_finish}", 25).first.id
    @my_reports = current_user.reports.where("period = ?", params[:period])
    @period = params[:period]

  end

  def update
    @report = Report.find(params[:id])
    @report.update_attributes(report_params)
    @report.save
    hello = []
    redirect_to my_reports_user_reports_path
  end
    
  
  def show
  end

  def edit
    @report = Report.find(params[:id])
    @month = Time.now.month
    if    [1,2,3,4].include?(@month) then @default_period = 1 end
    if    [5,6,7,8].include?(@month) then @default_period = 2 end
    if [9,10,11,12].include?(@month) then @default_period = 3 end    
    @my_reports = current_user.reports
    @array_for_options = Course.array_for_options
    @array_for_days = Course.array_for_days
    @array_for_period = [["Invierno", 1], ["Verano", 2], ["Otoño", 3]]
  end

  def create

    @report = current_user.reports.new(report_params)
    @report.save
    redirect_to :back

  end

  def destroy
    @report = Report.find(params[:id])
    @report.destroy
    redirect_to my_reports_user_reports_path
  end

  def index

  end

  private
  def report_params
    allow = [:course_id, :week_day, :course_start_time, :period]
    params.require(:report).permit(allow)
  end

end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_calendar_nav.html.erb
<ul class="requested_month_list">
	<div id="period_cuarter_names">
<li><%= link_to "Invierno", :controller => "reports", :action => "calendar_reports", :period => 1 %> </li>
<li><%= link_to "Verano",   :controller => "reports", :action => "calendar_reports", :period => 2 %> </li>
<li><%= link_to "Otoño",    :controller => "reports", :action => "calendar_reports", :period => 3 %> </li>
	</div>
	<div id="period_months">
	<%= render "reports/calendar_nav_months" %>	
	</div>

</ul>	

app/views/reports/_calendar_nav_months.html.erb
<% if @period == "1" %>

<li><%= link_to "Enero",   :controller => "reports", :action => "monthly_reports", :start => "Diciembre", :finish => "Enero"  , :period => @period %> </li>
<li><%= link_to "Febero",  :controller => "reports", :action => "monthly_reports", :start => "Enero"   ,  :finish => "Febrero", :period => @period %> </li>
<li><%= link_to "Marzo",  :controller => "reports", :action => "monthly_reports", :start =>  "Febrero" ,  :finish => "Marzo"   , :period => @period %> </li>
<li><%= link_to "Abril", :controller => "reports", :action => "monthly_reports", :start =>   "Marzo"   ,  :finish => "Abril"  , :period => @period %> </li>

<% elsif @period == "2" %>

<li><%= link_to "Mayo",   :controller => "reports", :action => "monthly_reports", :start => "Abril"  , :finish => "Mayo"  , :period => @period %> </li>
<li><%= link_to "Junio",  :controller => "reports", :action => "monthly_reports", :start => "Mayo"   , :finish => "Junio" , :period => @period %> </li>
<li><%= link_to "Julio",  :controller => "reports", :action => "monthly_reports", :start => "Junio" , :finish => "Julio"  , :period => @period %> </li>
<li><%= link_to "Agosto", :controller => "reports", :action => "monthly_reports", :start => "Julio", :finish => "Agosto"  , :period => @period %> </li>

<% elsif @period == "3" %>

<li><%= link_to "Septiembre",   :controller => "reports", :action => "monthly_reports", :start => "Agosto"  , :finish => "Septiembre"  , :period => @period %> </li>
<li><%= link_to "Octubre",  :controller => "reports", :action => "monthly_reports", :start => "Septiembre"   , :finish => "Octubre" , :period => @period %> </li>
<li><%= link_to "Noviembre",  :controller => "reports", :action => "monthly_reports", :start => "Octubre" , :finish => "Noviembre"  , :period => @period %> </li>
<li><%= link_to "Diciembre", :controller => "reports", :action => "monthly_reports", :start => "Noviembre", :finish => "Diciembre"  , :period => @period %> </li>

<% end %>

app/views/reports/_report_list.html.erb
<ul class="report_list">
	<% for report in @my_reports %>
	<ul>
	<li class="first_time_in_report_list"><%= report.course_name %></li>
	<li class="last_time_in_report_list"><%= report.course_start_time.strftime("%I:%M %p") %></li>
	<li class="last_time_in_report_list"><%= report.week_day %></li>
	
	</ul>
	<% end %>
	<ul>

	

app/views/reports/calendar_reports.html.erb
	<%= render "reports/calendar_nav" %>		

<!-- <dl class="calendar_report_list">
	<% for report in @my_reports %>
	<dt> <%= report.course_name %>
		<dd>
			<% for day in report.calendars %>
	<li><%= day.week_day %></li>
	<li><%= day.month %></li>
	<li><%= day.day_of_month %></li>
	 <br />
			<% end %>
	</dd></dt>
	<% end %>
	<ul> -->

<br />
<br />
<br />

<ul class="report_list">
	<% for report in @my_reports %>
	<ul>
	<li class="first_time_in_report_list"><%= report.course_name %></li>
	<li class="last_time_in_report_list"><%= report.course_start_time.strftime("%I:%M %p") %></li>
	<li class="last_time_in_report_list"><%= report.week_day %></li>
	
	</ul>
	<% end %>
	<ul>

	

app/views/reports/create.html.erb
<h1>Reports#create</h1>
<p>Find me in app/views/reports/create.html.erb</p>

app/views/reports/destroy.html.erb
<h1>Reports#destroy</h1>
<p>Find me in app/views/reports/destroy.html.erb</p>

app/views/reports/edit.html.erb
<h2> <%= @report.course.name %> </h2>



<dl class="edit_report">
	<dd id="bold_dd">Programa:</dd>
		<dd><%= @report.course.program %></dd><br />
	<dd id="bold_dd">Cuatrimestre:</dt>
		<dd><%= @report.course.semester %></dd><br />
	<dd id="bold_dd">Creditos:</dt>
		<dd><%= @report.course.credits %></dd><br />
	<dd id="bold_dd">Area:</dt>
		<dd><%= @report.course.area %></dd><br />

	</dl>


	<h3> Editar clase </h3>

	<%= form_for @report do |f| %>

	<%= f.label :period %>
  <%= select(:report, :period, options_for_select(@array_for_period, @default_period)) %>

<!--   <%= f.label :course_id %>
  <%= select(:report, :course_id, options_for_select(@array_for_options)) %> -->

	<%= f.label :week_day %>
	<%= select(:report, :week_day, options_for_select(@array_for_days)) %>

	<%= f.label :course_start_time %>
	<%= f.time_select :course_start_time, {:minute_step => 30, ampm: true} %>

	<%= f.submit %>
	<%= link_to "Delete", @report, method: :delete%></li>
	<% end %>

app/views/reports/index.html.erb
<h1>Mis Clases</h1>
<p></p>

app/views/reports/monthly_reports.html.erb
	<%= render "reports/calendar_nav" %>	
	

<dl class="calendar_report_list">
	<% for report in @my_reports %>
	<dt> <%= report.course_name %>
		<dd>
			<% for day in report.month_interval(@start, @finish) %>
	<li><%= day.week_day %></li>
	<li><%= day.month %></li>
	<li><%= day.day_of_month %></li>
	 <br />
			<% end %>
	</dd></dt>
	<% end %>
	<ul>

app/views/reports/my_reports.html.erb
<h1>Mis Clases</h1>
<p></p>





<ul class="report_list">
	<% for report in @my_reports %>
	<ul>
	<li> <%= link_to "#{report.course_name}", edit_report_path(report) %></li>

	
	</ul>
	<% end %>
	<ul>

	

app/views/reports/new.html.erb
<div>
<ul class="report_list">
	<% for report in @my_reports %>
	<ul>
	<li><%= report.course_name %></li>
	</ul>
	<% end %>
	<ul>
	</div>



<div class="content">

<%= form_for Report.new do |f| %>

	<%= f.label :period %>
  <%= select(:report, :period, options_for_select(@array_for_period, @default_period)) %>

  <%= f.label :course_id %>
  <%= select(:report, :course_id, options_for_select(@array_for_options)) %>

	<%= f.label :week_day %>
	<%= select(:report, :week_day, options_for_select(@array_for_days)) %>

	<%= f.label :course_start_time %>
	<%= f.time_select :course_start_time, {:minute_step => 30, ampm: true} %>

	<%= f.submit %>
	<% end %>

<div class="content">

app/views/reports/show.html.erb
<h1>Reports#show</h1>
<p>Find me in app/views/reports/show.html.erb</p>